language: node_js
node_js:
  - "node"

script:
  - ng build --base-href https://myrhy.me/musualizer

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: dist/musualizer
  skip_cleanup: true
  on:
    branch: master
